---
- name: Ensure October installer path exists
  file:
    path: "{{ octobercms_installer_path }}"
    state: directory
  when: not octobercms_site_exists | bool

- name: Download October installer
  get_url:
    url: "{{ octobercms_installer_url }}"
    dest: "{{ octobercms_installer_path }}/installer"
  when: not octobercms_site_exists | bool

- name: Ensure October is installed
  command: php installer
  args:
    chdir: "{{ octobercms_installer_path }}"
  register: octobercms_installed
  failed_when: '"OctoberCMS successfully installed" not in octobercms_installed.stdout'
  when: not octobercms_site_exists | bool

- name: Remove October installer
  file:
    path: "{{ octobercms_installer_path }}/installer"
    state: absent
  when: not octobercms_site_exists | bool

- name: Generate encryption key
  command: php artisan key:generate
  args:
    chdir: "{{ octobercms_installer_path }}"
  register: octobercms_encryption_key_generated
  failed_when:
  - '"Application key" not in octobercms_encryption_key_generated.stdout'
  - '"set successfully" not in octobercms_encryption_key_generated.stdout'
  when: not octobercms_site_exists | bool