---
- name: Ensure OctoberCMS root path exists
  file:
    path: "{{ octobercms_root_path }}"
    state: directory
    owner: "{{ octobercms_owner }}"
    group: "{{ octobercms_owner }}"
    mode: 0775
  when: not octobercms_site_exists

- name: Download OctoberCMS installer
  get_url:
    url: "{{ octobercms_installer_url }}"
    dest: "{{ octobercms_root_path }}/installer"
  when: not octobercms_site_exists
  become: no

- name: Ensure OctoberCMS is installed
  command: php installer
  args:
    chdir: "{{ octobercms_root_path }}"
  register: octobercms_installed
  failed_when: '"OctoberCMS successfully installed" not in octobercms_installed.stdout'
  when: not octobercms_site_exists
  become_user: "{{ octobercms_owner }}"

- name: Remove OctoberCMS installer
  file:
    path: "{{ octobercms_root_path }}/installer"
    state: absent
  when: not octobercms_site_exists

- name: Generate encryption key
  command: php artisan key:generate
  args:
    chdir: "{{ octobercms_root_path }}"
  register: octobercms_encryption_key_generated
  failed_when:
  - '"Application key" not in octobercms_encryption_key_generated.stdout'
  - '"set successfully" not in octobercms_encryption_key_generated.stdout'
  when: not octobercms_site_exists