---
- name: Ensure OctoberCMS composer project path exists
  file:
    path: "{{ octobercms_composer_project_path }}"
    state: directory
  when: not octobercms_site_exists

- name: Create OctoberCMS composer project (this can take a while)
  composer:
    command: create-project
    arguments: "{{ octobercms_composer_package }} {{ octobercms_composer_project_path }}"
    working_dir: "{{ octobercms_composer_project_path }}"
    prefer_dist: "{{ octobercms_composer_prefer_dist }}"
    no_dev: "{{ octobercms_composer_no_dev }}"    
    optimize_autoloader: no
  when: not octobercms_site_exists

- name: Disable OctoberCMS core updates
  replace:
    path: "{{ octobercms_composer_project_path }}/{{ octobercms_cms_config_path }}"
    regexp: "('disableCoreUpdates'\\s*=>\\s*)(.*?)(,)"
    replace: '\1true\3'
  when: not octobercms_site_exists
