---
- name: Check if a composer.json file exists
  stat:
    path: "{{ octobercms_root_path }}/composer.json"
  register: octobercms_deploy_composer_json_file

- name: Check if a composer.lock file exists
  stat:
    path: "{{ octobercms_root_path }}/composer.lock"
  register: octobercms_deploy_composer_lock_file

- name: Run composer update if composer.lock doesn't exist (this can take a while)
  composer:
    command: update
    working_dir: "{{ octobercms_root_path }}"
    no_dev: "{{ octobercms_composer_no_dev }}"
  register: octobercms_deploy_composer_updated
  when:
  - octobercms_deploy_composer_json_file.stat.exists
  - not octobercms_deploy_composer_lock_file.stat.exists

- name: Run composer install if composer.lock exists (this can take a while)
  composer:
    command: install
    working_dir: "{{ octobercms_root_path }}"
    no_dev: "{{ octobercms_composer_no_dev }}"
  when:
  - octobercms_deploy_composer_lock_file.stat.exists
  - not octobercms_deploy_composer_updated.changed