---
- name: Configure application name
  replace:
    path: "{{ octobercms_root_path }}/{{ octobercms_app_config_path }}"
    regexp: "('name'\\s*=>\\s*')(.*?)(',)"
    replace: "\\1{{ octobercms_app_name | default('\\2') }}\\3"

- name: Configure application URL and debug mode
  replace:
    path: "{{ octobercms_root_path }}/{{ octobercms_app_config_path }}"
    regexp: "(?P<start>'{{ item.key }}'\\s*=>\\s*'?)(?P<current_value>.*?)(?P<end>'?,)"
    replace: "\\g<start>{{ item.value }}\\g<end>"
  with_dict:
  - debug: "{{ octobercms_app_debug | default(false) | ternary('true', 'false') }}"
  - url: "{{ octobercms_app_url | default('\\g<current_value>') }}"
  when: not octobercms_use_dotenv_config