---
- name: Ensure .env file exists
  command: php artisan october:env
  args:
    chdir: "{{ octobercms_root_path }}"
    creates: "{{ octobercms_root_path }}/.env"
  register: octobercms_env_installed

- name: Set APP_ENV variable
  lineinfile:
    path: "{{ octobercms_root_path }}/.env"
    regexp: '^APP_ENV='
    line: APP_ENV={{ octobercms_app_environment }}
    insertbefore: BOF
  when: octobercms_app_environment is defined

- name: Configure .env file
  lineinfile:
    path: "{{ octobercms_root_path }}/.env"
    regexp: '(?P<start>{{ item.key | upper }}=)(?P<current_value>.*)'
    line: "\\g<start>{{ item.value }}"
    backrefs: yes
  with_dict:
  - app_debug: "{{ octobercms_app_debug | ternary('true', 'false') }}"
  - app_url: "{{ octobercms_app_url | default('\\g<current_value>') }}"
  - app_key: "{{ octobercms_app_key | default('\\g<current_value>') }}"
  - db_connection: "{{ octobercms_database_connection | default('\\g<current_value>') }}"
  - db_host: "{{ octobercms_database_host | default('\\g<current_value>') }}"
  - db_port: "{{ octobercms_database_port | default('\\g<current_value>') }}"
  - db_database: "{{ octobercms_database_name | default('\\g<current_value>') }}"
  - db_username: "{{ octobercms_database_user | default('\\g<current_value>') }}"
  - db_password: "{{ octobercms_database_password | default('\\g<current_value>') }}"
  - db_use_config_for_testing: "{{ octobercms_use_config_for_testing | ternary('true', 'false') }}"
  - routes_cache: "{{ octobercms_cms_enable_routes_cache | ternary('true', 'false') }}"
  - assets_cache: "{{ octobercms_cms_enable_assets_cache | ternary('true', 'false') }}"
  - database_templates: "{{ octobercms_cms_database_templates | ternary('true', 'false') }}"
  - enable_csrf: "{{ octobercms_cms_enable_csrf | ternary('true', 'false') }}"