---
- name: Ensure SSH key path exists
  file:
    path: "{{ octobercms_ssh_key_path }}"
    state: directory
    mode: 0700
  when: octobercms_deploy_deployment_key_path is defined

- name: Ensure SSH deployment key is present
  copy:
    src: "{{ octobercms_deploy_deployment_key_path }}"
    dest: "{{ octobercms_ssh_key_path }}/{{ octobercms_deployment_key_name }}"
    mode: 0400
  when: octobercms_deploy_deployment_key_path is defined

- name: Checkout application from repo
  git:
    repo: "{{ octobercms_deploy_repo }}"
    dest: "{{ octobercms_deploy_path }}"
    version: "{{ octobercms_deploy_version }}"
    accept_hostkey: true
    force: true
    depth: "{{ octobercms_deploy_depth | default(omit) }}"
  register: octobercms_deploy_repo_installed
  notify: clear cache
  when:
  - octobercms_deploy_deployment_key_path is not defined

- name: Checkout application from repo using SSH deployment key
  git:
    repo: "{{ octobercms_deploy_repo }}"
    dest: "{{ octobercms_deploy_path }}"
    version: "{{ octobercms_deploy_version }}"
    key_file: "{{ octobercms_ssh_key_path }}/{{ octobercms_deployment_key_name }}"
    accept_hostkey: true
    force: true
    depth: "{{ octobercms_deploy_depth | default(omit) }}"
  register: octobercms_deploy_repo_installed
  notify: clear cache
  when:
  - octobercms_deploy_deployment_key_path is defined

- name: Update octobercms_site_exists
  set_fact:
    octobercms_site_exists: "{{ octobercms_deploy_repo_installed is defined | default(false) }}"

- name: Remove SSH deployment key
  file:
    path: "{{ octobercms_ssh_key_path }}/{{ octobercms_deployment_key_name }}"
    state: absent
  when: octobercms_deploy_deployment_key_path is defined