---
- name: Check if October is already installed
  stat:
    path: "{{ octobercms_root_path }}/index.php"
  register: octobercms_site

- name: Define octobercms_site_exists
  set_fact:
    octobercms_site_exists: "{{ octobercms_site.stat.exists | default(false) }}"

- include_tasks: deploy.yml
  when: octobercms_deploy | bool

- include_tasks: build-from-installer.yml
  when: octobercms_build_from_installer | bool

- include_tasks: build-from-composer.yml
  when: octobercms_build_from_composer | bool

- name: Run composer install (this can take a while)
  composer:
    command: install
    working_dir: "{{ octobercms_root_path }}"
    no_dev: "{{ octobercms_composer_no_dev }}"
  when: octobercms_composer_install | bool

- include_tasks: configure-app.yml
- include_tasks: configure-database.yml

- include_tasks: configure-dotenv.yml
  when: octobercms_use_dotenv_config | bool

- include_tasks: post-installation.yml