---
- name: Check if OctoberCMS is already installed
  stat:
    path: "{{ octobercms_root_path }}/index.php"
  register: octobercms_site

- name: Define octobercms_site_exists
  set_fact:
    octobercms_site_exists: "{{ octobercms_site.stat.exists | default(false) }}"

- include_tasks: deploy.yml
  when: octobercms_deploy | bool

- include_tasks: build-from-installer.yml
  when: octobercms_build_from_installer | bool

- include_tasks: build-from-composer.yml
  when: octobercms_build_from_composer | bool

- include_tasks: composer-install.yml
  when: octobercms_composer_install | bool

- include_tasks: configure-app.yml
- include_tasks: configure-database.yml

- include_tasks: configure-dotenv.yml
  when: octobercms_use_dotenv_config | bool

- name: Migrate database
  command: php artisan october:up
  args:
    chdir: "{{ octobercms_root_path }}"
  register: octobercms_migrate_database
  changed_when: '"Migration table created" in octobercms_migrate_database.stdout'

- name: Remove OctoberCMS demo theme and plugin
  command: php artisan october:fresh
  args:
    chdir: "{{ octobercms_root_path }}"
  register: octobercms_demo_removed
  when: octobercms_remove_demo | bool
  changed_when: '"Demo has been removed" in octobercms_demo_removed.stdout'